### ISSUE TITLE
如何用排槍控制器使用

### ISSUE THREAD

**Issue by power7714** [mumaoxi/UninstallFeedback#1]
@mumaoxi 
我如何使用這個，如果我的應用程序類是凌空控制器？如果沒有別的應用程序類，但凌空控制器類有很多的它正常工作。在凌空控制器類的onCreate（）方法具有這樣的：

`private static VolleyController instance`
`   @Override
    public void onCreate() {
        super.onCreate();
        UninstallFB.init(this, "http://www.google.com");
        instance = this;

```
}`
```

請只要你能有所幫助。

**Comment by nicolasyiu** [comment]
``` java
UninstallFB.init(this, "http://www.google.com"); // make 'this' is an object of Context 
```

**Comment by power7714** [comment]
@mumaoxi so I can replace "this" with `getApplicationContext`?

**Comment by nicolasyiu** [comment]
sure
